#!/usr/bin/env bash

# Icon directory
iDIR="$HOME/.config/HyprV/mako/icons"

# Get current brightness level
get_backlight() {
    LIGHT=$(brightnessctl g)
    MAX_LIGHT=$(brightnessctl m)
    PERCENT=$(printf "%.0f\n" $(echo "($LIGHT/$MAX_LIGHT)*100" | bc -l))
    echo "${PERCENT}%"
}

# Determine the correct icon based on brightness percentage
get_icon() {
    current=$(get_backlight)
    current="${current%%%}"
    
    if [[ ("$current" -ge "0") && ("$current" -le "20") ]]; then
        icon="$iDIR/brightness-20.png"
    elif [[ ("$current" -gt "20") && ("$current" -le "40") ]]; then
        icon="$iDIR/brightness-40.png"
    elif [[ ("$current" -gt "40") && ("$current" -le "60") ]]; then
        icon="$iDIR/brightness-60.png"
    elif [[ ("$current" -gt "60") && ("$current" -le "80") ]]; then
        icon="$iDIR/brightness-80.png"
    else
        icon="$iDIR/brightness-100.png"
    fi
}

# Notify user with the current brightness level and corresponding icon
notify_user() {
    notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$icon" "Brightness: $(get_backlight)"
}

# Increase brightness
inc_backlight() {
    brightnessctl set 10%+ && get_icon && notify_user
}

# Decrease brightness
dec_backlight() {
    brightnessctl set 10%- && get_icon && notify_user
}

# Execute accordingly based on the input argument
case "$1" in
    --get)
        get_backlight
        ;;
    --inc)
        inc_backlight
        ;;
    --dec)
        dec_backlight
        ;;
    *)
        get_backlight
        ;;
esac
