#!/usr/bin/env bash

iDIR="$HOME/.config/HyprV/mako/icons"

# Get current keyboard backlight brightness percentage
get_backlight() {
    LIGHT=$(brightnessctl -d '*::kbd_backlight' g)
    MAX_LIGHT=$(brightnessctl -d '*::kbd_backlight' m)
    PERCENT=$(printf "%.0f\n" $(echo "($LIGHT/$MAX_LIGHT)*100" | bc -l))
    echo "${PERCENT}%"
}

# Determine the icon based on brightness percentage
get_icon() {
    backlight=$(brightnessctl -d '*::kbd_backlight' g)
    MAX_LIGHT=$(brightnessctl -d '*::kbd_backlight' m)
    current=$(printf "%.0f\n" $(echo "($backlight/$MAX_LIGHT)*100" | bc -l))

    if [[ "$current" -le 33 ]]; then
        icon="$iDIR/brightness-20.png"
    elif [[ "$current" -le 66 ]]; then
        icon="$iDIR/brightness-60.png"
    else
        icon="$iDIR/brightness-100.png"
    fi
}

# Send a notification with the current brightness level
notify_user() {
    notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$icon" "Keyboard Brightness: $(get_backlight)"
}

# Increase keyboard backlight brightness
inc_backlight() {
    brightnessctl -d '*::kbd_backlight' set 33%+ && get_icon && notify_user
}

# Decrease keyboard backlight brightness
dec_backlight() {
    brightnessctl -d '*::kbd_backlight' set 33%- && get_icon && notify_user
}

# Execute commands based on the provided argument
case "$1" in
    --get)
        get_backlight
        ;;
    --inc)
        inc_backlight
        ;;
    --dec)
        dec_backlight
        ;;
    *)
        get_backlight
        ;;
esac
