#!/usr/bin/env bash

# Check if the script is running on Gentoo
if [ ! -d /etc/portage ]; then
    exit 0
fi

# Calculate updates
calculate_updates() {
    # Sync Portage tree and update eix
    emerge --sync --quiet
    eix-update -q
    
    # Capture the output of 'emerge -uD --pretend @world'
    local updates
    updates=$(emerge -uD --pretend @world | grep '^ \[ebuild U\]' | wc -l)
    
    echo "$updates"
}

# Get the number of available updates
UPDATE_COUNT=$(calculate_updates)

# Case/switch for each service updates
case $1 in
    official) echo " $UPDATE_COUNT";;
esac

# If the parameter is "update", update all packages
if [ "$1" = "update" ]; then
    kitty --title update-sys sh -c 'emerge -uD @world'
fi

# If there aren't any parameters, return the total number of updates
if [ -z "$1" ]; then
    if [ "$UPDATE_COUNT" -eq 0 ]; then
        echo ""
    else
        echo " $UPDATE_COUNT"
    fi
    exit 0
fi
