#!/usr/bin/env bash

# Original script adapted for Gentoo

# If the operating system is not Gentoo, exit the script successfully
if [ ! -d /etc/portage ]; then
    exit 0
fi

# Calculate updates for each service
# This assumes you have `eix` installed for quick package database queries.
AUR=0  # Gentoo doesn't use AUR, so we set it to 0
OFFICIAL=$(emerge --sync --quiet; eix-update -q; eix -I --only-names --version | wc -l)

# Case/switch for each service updates
case $1 in
    aur) echo "No AUR equivalent in Gentoo";;
    official) echo " $OFFICIAL";;
esac

# If the parameter is "update", update all packages
if [ "$1" = "update" ]; then
    kitty --title update-sys sh -c 'emerge --sync && emerge -avuDN @world'
fi

# If there aren't any parameters, return the total number of updates
if [ "$1" = "" ]; then
    # Calculate total number of updates
    COUNT=$((OFFICIAL+AUR))

    if [[ "$COUNT" = "0" ]]; then
        echo ""
    else
        # Display the update symbol and count
        echo " $COUNT"
    fi
    exit 0
fi
